### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by alberto-bc** [H21lab/json2pcap#5]
Hi! I have a capture file with [embedded decryption secrets](https://wiki.wireshark.org/TLS), which I exported as a JSON file. I was hoping this project could reconstruct a pcap with the JSON data, but the generated file only displays [Malformed Packet] information. 

Is this a feature you are considering in the future?

**Comment by H21lab** [comment]
Hi @alberto-bc . If possible please provide an example of json what you would like to reconstruct. Thank you

**Comment by alberto-bc** [comment]
Used Python 2.7.16

Please rename the file to json
[70.zip](https://github.com/H21lab/json2pcap/files/5424718/70.zip)

**Comment by H21lab** [comment]
The json2pcap can be used only for json generated with `tshark -T json -x` or `tshark -T jsonraw`. This will add raw hex fields into json. Attached pcap does not include the raw fields.

**Comment by alberto-bc** [comment]
You're right, the exported data was in the wrong format. I attached the [raw](https://github.com/H21lab/json2pcap/files/5430921/raw.zip) json
 export. The reconstructed pcap is smaller than the original capture file used to export the json data (no http data in the reconstructed pcap)

**Comment by H21lab** [comment]
To be able to investigate it, you have to provide the original pcap and to describe what is expected. 
I guess it is HTTPs traffic there and use embedded decryption secrets. So in wireshark you see the HTTP traffic. However I'm not sure if this is supported by tshark and what exact pcap reconstruction you would expect from HTTPs traffic.

To reconstruct the pcap I have used `cat raw.json | python json2pcap.py -o ./raw.pcap`.
